### PR TITLE
feat: Added basic support for PWA

### PR DESCRIPTION
**Pull request by sud0bug**
Added basic files required to convert the app to PWA. 
Made the app installable and setup service workers.
Closes issue https://github.com/monad-devrel/monad-discord-auth/issues/4

### CODE REVIEW

**Comment by portdeveloper** [comment]
Hey this is looking great with the salmonad! 

But I couldn't find where the service workers are implemented

**Comment by sud0bug** [comment]
Hi @portdeveloper, I am using https://github.com/shadowwalker/next-pwa plugin for PWA implementation and service workers are generated on build time (Hence added to .gitignore). It abstracts out almost all SW configs to next.config configs.

**Comment by portdeveloper** [comment]
Thanks for the info! I didn't know that. 

image
Could you also have a look at these errors when you have some time?
You can use https://www.pwabuilder.com/imageGenerator to generate appropriately sized images.

**Comment by sud0bug** [comment]
Closed and reopened in https://github.com/monad-devrel/monad-discord-auth/pull/11/

**Pull request closed without merging**
