### PR TITLE
Updated the wording

### PR DESCRIPTION
**Pull request by Rahul-2006**
Changed the wording of verification if you are a nad

### CODE REVIEW

**Comment by Rahul-2006** [comment]
I have updated the wording please check it and if you want any other please let me know

**Comment by portdeveloper** [comment]
Do you think it could be better if it was something else? Because calling them roles could be better.

**Comment by Rahul-2006** [comment]
I guess it's fine 
If you have like a particular issue please let me know

**Review by portdeveloper — APPROVED** [review]
Thanks! I think we can merge this as it is and make necessary adjustments later!

**Comment by Rahul-2006** [comment]
Thank you so much brother
It helps me in growing💗

**Pull request merged**
